### PR TITLE
mesa: enable tools package

### PR DESCRIPTION
**Pull request by lumag**
Mesa can provide several tools which simplify debugging mesa and the kernel driver. Enable them to be built into the mesa-tools package.

### CODE REVIEW

**Comment by ndechesne** [comment]
Why in meta-qcom, and not in the main oe-core recipe?

**Comment by lumag** [comment]
> Why in meta-qcom, and not in the main oe-core recipe?

What exactly? The build fix or the tools enablement?

**Comment by ndechesne** [comment]
I thought both. But I looked into it a bit more.. the patch probably should go to oe-core, the PACKAGECONFIG maybe not..

**Comment by lumag** [comment]
Done, the musl fixup was accepted into oe-core.

**Pull request merged**
