### PR TITLE
recipes-graphics: mesa_git bump to rev aed8d30b50

### PR DESCRIPTION
**Pull request by alimon**

### CODE REVIEW

**Comment by lumag** [comment]
Reviewed-by: Dmitry Baryshkov

**Comment by ndechesne** [comment]
does the build fail if we pass the PACKAGECONFIG?

**Comment by lumag** [comment]
> does the build fail if we pass the PACKAGECONFIG?

This might be a cleaner solution:
```
PLATFORMS_remove = "drm surfaceless"
```

**Comment by ndechesne** [comment]
> > does the build fail if we pass the PACKAGECONFIG?
> 
> This might be a cleaner solution:
> 
> ```
> PLATFORMS_remove = "drm surfaceless"
> ```

probably. That said I was interesting to understand why we needed this change. I have now looked at the upstream commit, and I understand. But perhaps a better commit message would be helpful.

**Comment by alimon** [comment]
@ndechesne  @lumag I updated the commit to remove platforms instead.

**Pull request merged**
