### PR TITLE
Kernel recipe patches, part2 bootimg-related cleanup, v3

### PR DESCRIPTION
**Pull request by madisongh**
#22 with comments incorporated

### CODE REVIEW

**Comment by ndechesne** [comment]
merged a slightly modified version (i have only move the symlink creation for the DT image in the last commit).

**Comment by ndechesne** [comment]
btw, thanks a lot for your patches!

**Comment by ndechesne** [comment]
and btw (again), I have boot tested images on DB820c and IFC6410.

**Comment by ndechesne** [comment]
hi, i just realized that there is a small issue with 589bbe8, before that patch, the symlink for the boot image was boot-${MACHINE}.img, and now that it has become boot-${KERNEL_IMAGE_SYMLINK_NAME}.img which corresponds to boot-${KERNEL_IMAGETYPE}-${MACHINE}.img.. Was it really intentional? I can fix it up in 2 ways:
1. change it back to what it was
2. make an additional symlink, in case you really wanted to have the one you did..

**Comment by madisongh** [comment]
Sorry, that difference slipped my mind when I put together the patches.  Including the image type in the symlink is more aligned with how naming works for other platforms, and allows for the possibility that at some point there will be multiple kernel image types.

I think the second approach would be better, to have the backward compatibility in naming but making it easier to implement later-stage image creation/packaging that could work across multiple platforms without having to special-case the naming difference.

**Comment by ndechesne** [comment]
i prefer #2 as well, i will do that quickly.

**Comment by ndechesne** [comment]
now that I look even closer at it.. KERNEL_IMAGE_SYMLINK_NAME definition has changed in master (after krogoth), in 849b67b2e4820564b5e5c9bd4bb293c44351c5f3. So we only need the fixup in krogoth branch in fact..

**Pull request closed without merging**
