### PR TITLE
CI: tuxsuite: Remove wrong entry in artifacts field

### PR DESCRIPTION
**Pull request by vishalbhoj**
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>

### CODE REVIEW

**Comment by vishalbhoj** [comment]
artifacts list now expects a list of right directory path relative to deploy_dir path. By default it publishes complete deploy directory

**Comment by lumag** [comment]
@vishalbhoj The commit doesn't tell why the entry is wrong. Also the original intent was obviously to keep deployed files in artifacts. If it is a default, it should be mentioned in the commit message.

**Comment by ndechesne** [comment]
Why are you limiting the artifacts to be in DEPLOY_DIR? there could be other useful artifacts, such as log, stamps, .. or binary files when debugging specific issues.

**Comment by vishalbhoj** [comment]
@lumag I have improved the commit message to describe the right behavior.

@ndechesne We will support other artifacts outside of deploy_dir in future as planned.

**Review by lumag — APPROVED** [review]

**Pull request merged**
