### PR TITLE
recipes-graphics: mesa_git bump to rev ec74a13618  and add MESA_DEV variable

### PR DESCRIPTION
**Pull request by alimon**

### CODE REVIEW

**Comment by alimon** [comment]
@ndechesne I reviewed devupstream class and only allow to specify git and rev by config file,

We have,

SRC_URI = "git://git.example.com/example"
SRCREV_pn-mesa = "${AUTOREV}" 

Vs,

SRC_URI_class-devupstream = "git://git.example.com/example"
SRCREV_class-devupstream = "${AUTOREV}

Still the maintainence is need when codebase changes, like this one to refresh some patches and fix installation of ci files due to mesa upstream change.

**Comment by ndechesne** [comment]
but at least we wouldn't need to update for each commit, and we would get latest commit in each build. isn't that better?

**Comment by alimon** [comment]
> but at least we wouldn't need to update for each commit, and we would get latest commit in each build. isn't that better?

@ndechesne Still we will nedd to bump the SRCREV at certain time, I can add AUTOREV in the mesa_git recipe but once in a while we will have broken builds. I not added AUTOREV in mesa_git before because @lumag was using certain sha of mesa_git for RB5 release.

**Comment by alimon** [comment]
@ndechesne I tried to use devupstream class but found a bug with nativesdk providers for mesa.

I added the devupstream class support into the bbappend that we have,


--- a/recipes-graphics/mesa/mesa_%.bbappend
+++ b/recipes-graphics/mesa/mesa_%.bbappend
@@ -1,4 +1,4 @@
-FILESEXTRAPATHS_prepend := "${THISDIR}/${BPN}:"
+FILESEXTRAPATHS_prepend := "${THISDIR}/${BPN}:${THISDIR}/files:"
 
 # Enable freedreno driver
 PACKAGECONFIG_FREEDRENO = "\
@@ -7,3 +7,36 @@ PACKAGECONFIG_FREEDRENO = "\
 "
 
 PACKAGECONFIG_append_qcom = "${PACKAGECONFIG_FREEDRENO}"
+
+# Add support to build mesa dev
+BBCLASSEXTEND = "devupstream:target"
+SRC_URI_class-devupstream = "git://gitlab.freedesktop.org/mesa/mesa.git;protocol=https \
+    file://0001-meson.build-check-for-all-linux-host_os-combinations.patch \
+    file://0002-meson.build-make-TLS-ELF-optional.patch \
+    file://0003-Allow-enable-DRI-without-DRI-drivers.patch \
+    file://0004-Revert-mesa-Enable-asm-unconditionally-now-that-gen_.patch \
+    file://0001-meson-misdetects-64bit-atomics-on-mips-clang.patch \
+"
+LIC_FILES_CHKSUM_class-devupstream = "file://docs/license.rst;md5=9aa1bc48c9826ad9fdb16661f6930496"
+
+SRCREV_class-devupstream = "13f92183c7dbff9d76a83656862d0b2c2536e25d"
+
+PLATFORMS_remove_class-devupstream = "drm surfaceless"
+PACKAGECONFIG_class-devupstream[osmesa] = "-Dosmesa=true,-Dosmesa=false"
+
+PV_class-devupstream = "20.4-dev+git${SRCPV}"
+
+# Add package to install require files to run tests for mesa
+PACKAGES_class-devupstream =+ "mesa-ci"
+FILES_${PN}-ci_class-devupstream = "${bindir}/deqp-runner.sh ${datadir}/mesa/deqp-*"
+do_install_append_class-devupstream () {
+    install -d ${D}/${datadir}/mesa
+
+    install -m 0644 ${S}/ci-expects/default/deqp-default-skips.txt ${D}/${datadir}/mesa/
+    for f in ${S}/ci-expects/freedreno/deqp-freedreno-*; do
+        install -m 0644 $f ${D}/${datadir}/mesa/
+    done
+
+    install -d ${D}/${bindir}
+    install -m 0755 ${S}/.gitlab-ci/deqp-runner.sh ${D}/${bindir}/
+}

Basically I added some missing nativesdk mesa providers like in poky has but the chain was not solve.

diff --git a/conf/machine/include/qcom-common.inc b/conf/machine/include/qcom-common.inc
index fd86574..bbf35a8 100644
--- a/conf/machine/include/qcom-common.inc
+++ b/conf/machine/include/qcom-common.inc
@@ -17,8 +17,12 @@ XSERVER ?= " \
 
 PREFERRED_PROVIDER_virtual/egl ?= "mesa"
 PREFERRED_PROVIDER_virtual/libgl ?= "mesa"
+PREFERRED_PROVIDER_virtual/libgl-native ?= "mesa-gl-native"
 PREFERRED_PROVIDER_virtual/libgles1 ?= "mesa"
 PREFERRED_PROVIDER_virtual/libgles2 ?= "mesa"
+PREFERRED_PROVIDER_virtual/nativesdk-egl ?= "virtual/nativesdk-mesa"
+PREFERRED_PROVIDER_virtual/nativesdk-libgl ?= "nativesdk-mesa-gl"
+PREFERRED_PROVIDER_nativesdk-mesa ?= "nativesdk-mesa"
 PREFERRED_PROVIDER_virtual/xserver ?= "xserver-xorg"
 PREFERRED_PROVIDER_virtual/kernel ?= "linux-linaro-qcomlt"
 

Results,

...
ERROR: Required build target 'mesa' has no buildable providers.
Missing or unbuildable dependency chain was: ['mesa', 'expat', 'bash', 'coreutils', 'acl', 'e2fsprogs-mke2fs', 'procps', 'systemd', 'dbus', 'dbus-test-ptest', 'glib-2.0', 'shared-mime-info', 'libxml2', 'python3', 'util-linux', 'kernel-module-scsi-debug', 'initramfs-rootfs-image', 'nativesdk-packagegroup-sdk-host', 'nativesdk-qemu', 'nativesdk-virglrenderer', 'nativesdk-libepoxy', 'virtual/nativesdk-egl']
...

**Comment by alimon** [comment]
@ndechesne I added MESA_DEV variable to switch from AUTOREV to fixed REV and also is used to switch DEFAULT_PREFERENCE.

**Pull request merged**
