### PR TITLE
Update alsa ucm scripts for dunfell

### PR DESCRIPTION
**Pull request by lumag**
Depends: https://review.linaro.org/c/openembedded/meta-backports/+/37730
https://review.linaro.org/c/openembedded/meta-backports/+/37729

### CODE REVIEW

**Comment by lumag** [comment]
@alimon this is a backport of current master patches + #260 to Dunfell.
Could you please check that it works for you (note the meta-backports dependencies).

@ndechesne this is another PR targeting forthcoming RB5 release.

**Comment by ndechesne** [comment]
I suppose we don't really need patch #2 and #3 in dunfell, since #4 does it all again. perhaps we can clean up the PR?

**Comment by lumag** [comment]
@ndechesne cleaned up the PR

**Comment by alimon** [comment]
@lumag I checked 1.2.4 on Debian and is working in DB410c and DB845c, is ok to me merge the backports.

**Pull request merged**
