### PR TITLE
machines: Adjust for new tune file locations in core

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
Please hold on merging this until [1] is merged into OE-core

[1] https://lists.openembedded.org/g/openembedded-core/topic/patch_v2_0_3_tunes_the/84935312?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,84935312

**Comment by kraj** [comment]
Please merge this now since relevant OE-core commit is not in master.

**Comment by lumag** [comment]
@kraj @alimon 
CI fails, because we are missing host tools: https://review.linaro.org/c/ci/job/configs/+/39528

**Comment by kraj** [comment]
Seems unrelated to this pull though ?

**Pull request merged**
